# bundle exec jekyll serve --watch

# Site settings
title: "Scholars’ Lab"
name: "Scholars’ Lab"
email: scholarslab@virginia.edu
description: "The Scholars’ Lab"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maybe.scholarslab.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scholarslab
permalink: /:year/:month/:day/:title/
timezone: America/New_York
# Build settings
analytics: false
incremental: true
sass:
  sass_dir: assets/css/_sass
  style: compressed
markdown: kramdown
kramdown: 
  parse_block_html: true
  parse_span_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - docs
  - node_modules
  - theme-testing
#  - _posts # temporary! significantly reduces build time for theme testing
#  - _people # temporary
  - assets/python # helper scripts to manipulate HTML/CSS, not used in build

collections_dir: collections
collections:
  people:
    output: true
    permalink: /:collection/:slug/
  work:
    output: true
    permalink: /:collection/:name/
  events:
    output: true
    permalink: /:collection/:name/
  spaces: # output false

header_pages:
  - about.md
  - people.md
  - blog.md
  - work.md
  - search.html

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "pages"
    values:
      order: 10
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      og_type: "article"
  - scope:
      path: ""
      type: "pages"
    values:
      is_page: true
      og_type: "website"
