# bundle exec jekyll serve --watch

# Site settings
title: "Scholars’ Lab"
name: "Scholars’ Lab"
email: scholarslab@virginia.edu
description: "The Scholars’ Lab"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scholarslab.lib.virginia.edu" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/
timezone: America/New_York
# Build settings
analytics: true
sass:
  sass_dir: assets/css/_sass
  style: compressed
markdown: kramdown
highlighter: rouge
kramdown:
  parse_block_html: true
  parse_span_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - docs
  - node_modules
  - theme-testing
#  - _posts # temporary! uncomment to significantly reduce build time for theme testing
#  - _people # temporary, uncomment to reduce testing build time
  - assets/python # helper scripts to manipulate HTML/CSS, not used in build

collections_dir: collections
collections:
  people:
    output: true
    permalink: /:collection/:slug/
  work:
    output: true
    permalink: /:collection/:name/
  events:
    output: true
    permalink: /:collection/:name/
  spaces: # output false

header_pages:
  - about.md
  - expertise.md
  - collaborate.md
  - community.md
  - scholarship.html

## Nested list for primary navigation.
primary-navigation:
  - label: "About"
    url: "for-students"
  - label: "Expertise"
    url: "expertise"
  - label: "Collaborate"
    url: "collaborate"
  - label: "Community"
    url: "community"
  - label: "Scholarship"
    url: "scholarship"

about-navigation:
  - "about/about.md"
  - "about/people.md"
  - "about/charter.md"
  
expertise-navigation:
  - "expertise/dh-code-design/dh-code-design.md"
  - "expertise/spatial-technologies/spatial-technologies.md"
  - "expertise/makerspace/makerspace.md"
  
collaborate-navigation:
  - "collaborate/for-students/for-students.md"
  - "collaborate/for-faculty/for-faculty.md"
  - "collaborate/for-everyone.md"
  
community-navigation:
  - "community/events.md"
  - "community/spaces-equipment.md"
  
scholarship-navigation:
  - "scholarship/work.md"
  - "scholarship/blog.md"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "posts"
    values:
      og_type: "article"
      permalink: /blog/:title/
  - scope:
      path: "pages"
      type: "pages"
    values:
      order: 10
      og_type: "website"
