# bundle exec jekyll serve --watch

# Site settings
title: "Scholars’ Lab"
name: "Scholars’ Lab"
email: scholarslab@virginia.edu
description: "The Scholars’ Lab"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scholarslab.lib.virginia.edu" # the base hostname & protocol for your site
permalink: /:title/
timezone: America/New_York
# Build settings
analytics: true
sass:
  sass_dir: assets/css/_sass
  style: compressed
markdown: kramdown
highlighter: rouge
kramdown:
  parse_block_html: true
  parse_span_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - docs

collections_dir: collections
collections:
  people:
    output: true
    permalink: /:collection/:slug/
  work:
    output: true
    permalink: /:collection/:name/
  events:
    output: true
    permalink: /:collection/:name/
  past-events:
    output: true
    permalink: /events/:name/

## Nested list for primary navigation.
primary-navigation:
  - label: "About"
    url: "about"
    subnavigation:
      - label: "People"
        url: "people"
      - label: "Charter"
        url: "charter"
      - label: "Accessibility"
        url: "accessibility"
  - label: "Consult"
    url: "consult"
    subnavigation:
      - label: "Spatial Tech"
        url: "spatial-technologies"
      - label: "Makerspace"
        url: "makerspace"
      - label: "Code + Design"
        url: "code-design"
      - label: "Digital Humanities"
        url: "digital-humanities"
  - label: "Opportunities"
    url: "opportunities"
    subnavigation:
      - label: "For Students"
        url: "for-students"
      - label: "For Faculty"
        url: "for-faculty"
      - label: "For Everyone"
        url: "for-everyone"
  - label: "Scholarship"
    url: "scholarship"
    subnavigation:
      - label: "Our Projects"
        url: "work"
      - label: "Blog"
        url: "blog"
  - label: "Visit"
    url: "visit"
    subnavigation:
      - label: "Use the Lab"
        url: "use-the-lab"
      - label: "Use the Makerspace"
        url: "makerspace#using-the-makerspace"
  - label: "Events"
    url: "events"
    subnavigation:
      - label: "Event Archive"
        url: "events-archive"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "posts"
    values:
      og_type: "article"
      permalink: /blog/:title/
  - scope:
      path: "pages"
      type: "pages"
    values:
      order: 10
      og_type: "website"
